steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${_PROJECT_ID}/code2duo", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${_PROJECT_ID}/code2duo"]

  - name: "gcr.io/google-appengine/exec-wrapper"
    args: ["-i", "gcr.io/${_PROJECT_ID}/code2duo",
           "-e", "STAGE=${_STAGE}",
           "-s", "${_PROJECT_ID}:${_REGION}:code2duo-instance",
           "--", "python", "manage.py", "migrate"]

  - name: "gcr.io/google-appengine/exec-wrapper"
    args: ["-i", "gcr.io/${_PROJECT_ID}/code2duo",
           "-e", "STAGE=${_STAGE}",
           "-s", "${_PROJECT_ID}:${_REGION}:code2duo-instance",
           "--", "python", "manage.py", "collectstatic", "--no-input"]
