# Generated by Django 3.1.7 on 2021-05-17 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('score_1', models.PositiveSmallIntegerField(default=0)),
                ('score_2', models.PositiveSmallIntegerField(default=0)),
                ('match_type', models.PositiveSmallIntegerField(choices=[(1, 'Onevone'), (2, 'Twovtwo')], default=1)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(default=60)),
                ('winner', models.SmallIntegerField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.TextField()),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Noob'), (2, 'Intermediate'), (3, 'Pro')])),
                ('contests', models.ManyToManyField(blank=True, related_name='questions', to='core.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True)),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='Searching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=12, unique=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Onevone'), (2, 'Twovtwo')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')], null=True)),
                ('profile_img', models.URLField(blank=True, null=True)),
                ('state', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('programming_lang', models.PositiveSmallIntegerField(choices=[(1, 'C'), (2, 'Cpp'), (3, 'Java'), (4, 'Python')], default=2)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_questions_solved', models.IntegerField(default=0)),
                ('no_of_contests', models.IntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Noob'), (2, 'Intermediate'), (3, 'Pro')], null=True)),
                ('is_searching', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='participant_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contest_1', to='core.profile'),
        ),
        migrations.AddField(
            model_name='contest',
            name='participant_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contest_2', to='core.profile'),
        ),
    ]
