# Generated by Django 3.1.7 on 2021-05-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Noob'), (2, 'Intermediate'), (3, 'Pro')], default=1, null=True),
        ),
        migrations.CreateModel(
            name='MatchRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=12, unique=True)),
                ('participant_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.profile')),
                ('participant_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.profile')),
            ],
        ),
    ]
