# Generated by Django 3.1.7 on 2021-05-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210520_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='contests',
        ),
        migrations.AddField(
            model_name='contest',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='contest', to='core.Question'),
        ),
    ]
